### ISSUE TITLE
Crash on launch with Forge

### ISSUE THREAD

**Issue by kosakriszi** [DaFlight/DaFlight#1]
Forge version: 1.8.9-11.15.1.1764
DaFlight version: 1.8.9-3.1r1

Firstly, the stack trace: http://bin.ex.gg/foqecodoyu.css

It looks like your tweaker is duplicating the version argument for some reason, which is what the crash explains.
This issue occurs if i load it as a mod, and also if it is loaded as an actual tweak.

**Comment by dags-** [comment]
Mmm yeah, I compiled it with the wrong meta-inf details, which is causing that crash.

Doesn't actually seem to load at all when I correct the meta-inf, so I'll need to look into that and rebuild the mod. Hopefully I'll have time to put a fix up tomorrow - 1.8.8 should still work if that's an option.

Thanks for bringing this to my attention.

**Comment by kosakriszi** [comment]
Alright, sounds awesome!

**Comment by kosakriszi** [comment]
Any progress on this?

**Comment by dags-** [comment]
No sorry, I need to rebuild the jar in a 1.8.9 dev environment but I don't currently have one.
I think the new liteloader dev kit will be released for 1.8.9 "soon<sup>:tm:</sup>", so may wait to see what that's like

**Comment by mattmess1221** [comment]
You should try with the new release. Your stack trace expired, so I'm not sure what the problem was, but I did some changes that might have fixed it.

**Comment by dags-** [comment]
Still has issues with forge from what I have tested. Possibly/probably an issue with df's tweaker.
-snip-

**Comment by kosakriszi** [comment]
Apologies for the expiring paste! If further testing is needed, I am able to do so.

**Comment by dags-** [comment]
The crash you originally reported was due to a compile issue, which, technically, is fixed. Unfortunately however, the mod still doesn't work properly with forge.

My waffle above is a different issue. I've opened a for it [here](https://github.com/DaFlight/DaFlight/issues/5). Please do test and report any findings there.

**Comment by dags-** [comment]
All should<sup>TM</sup> be working in 3.1r3
