### ISSUE TITLE
compatibility issue with MoreCommands. Plus could you add an option to adjust the reach distance

### ISSUE THREAD

**Issue by jistjak** [DaFlight/DaFlight#10]
MoreCommnads mod causes Noclip to not work and causes fall damage when landing. I've been looking all over the web for a way to increase the reach distance and i really love this mod because it is just like the zombe modpack fly mod and also in zombe there was a reach adjustment, but since zombe is still in the stone age (not compatible with forge) i cant use zombe. and the extended reach mod has been dead for 6 years (since 1.5 beta). I came across the morecommands mod which can adjust the reach but that mod causes malfunctions with the DaFlight mod as i wrote above. If DaFlight mod can also increase the reach so i can build structures more than two - 4 blocks at a time, That would solve everything.

HERE IS WHAT I USED
Minecraft 1.8
DaFlight-Mod-1.8_2.4.r9
MoreCommands-1.8-2.7

**Comment by dags-** [comment]
I don't maintain for minecraft 1.8 any more, it's just far too out of date - I no-longer maintain a litemod version of daflight either.

Many of the hacks/features in Zombe's simply aren't possible any more without either getting a whole lot hackier, or requiring a server-side component.
Either way, won't be adding such things to daflight as they lie outside the scope of what the mod is for

**Comment by jistjak** [comment]
That's okay, I guess I'll work around this bug, since my minecraft 1.8
is modded and i really don't want to upgrade minecraft until there are
enough mods for the new version. I found a macro key binding mod that
can bind keys to commands. and just use the more command's noclip
instead of daflight. Thanks for your response though.
