### ISSUE TITLE
1.8.9 DaFlight not working in Mod packs

### ISSUE THREAD

**Issue by craigbrian** [DaFlight/DaFlight#12]
Every liteloader version I've tried  implentneting into Technic mod packs and all the liteloader mods have worked. Except this one 
I love this mod it has full bright and allows you to speed jump or fly. Is there a possbillty fixing this please without requiring a DaFlight profile jar?

**Comment by dags-** [comment]
Yep, totally possible. Use the 'extract' button in the daflight installer to get the actual mod jar. Just place that wherever you place the litemods, and liteloader should find and load it

**Comment by craigbrian** [comment]
Thanks for replying so fast. I all ready tried that like I said all the other Liteloader mods are working with modpacks it's only DaFlight that is not. It won't pop up in the modpack or the Liteloader
for this mod pack. The id for the modpack is 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
could this version of forge be interfering?

**Comment by dags-** [comment]
Please could you post a log (just launch the modpack to the title screen and grab the latest one)?

Should work just fine with forge installed as well. Either liteloader or forge will load the mod (it doesn't matter which), and the other will detect that it has already been loaded and just leave it alone.

**Comment by craigbrian** [comment]
I use Java 8 64 bit. Now this is interesting DaFlight-3.2r1-mc1.8.9 doesn't appear in mods on vanilla with forge1.8.9-11.15.1.1902-1.8.9 it does work but in the controls isn't listed so I can't change the controls to other keys.
It does load up in vanilla Liteloader with forge1.8.9-11.15.1.1902-1.8.9 still doesn't list the controls
If I install theDaFlight-3.2r1-mc1.8.9 profile and use it the controls still aren't listed.
Now in a modpack it does't show up at all and even if it did I'm using the Pixelmon mod and it uses the R key so I still wouldn't be able to change it in DaFlight.
also why did you change the way Fly works in 1.8.9? I miss the old way it worked better on all servers even with anti fly because you could still press F and it would kick you up to the last block.

**Comment by craigbrian** [comment]
I'm totally lost now everytinhg I have previously said was done on my Windows 7.
And now I just tried all of this over again on my Windows XP, and Windows 8 and DaFlight isn't working at all no matter what I do. It loads it into Liteloader and even if I reset the control it won't work. Here is a log from my XP running Java 8 Update 102

[2016-08-03-1.WinXPlog.zip](https://github.com/DaFlight/DaFlight/files/399548/2016-08-03-1.WinXPlog.zip)

**Comment by craigbrian** [comment]
I'm so confused of what is going on.

[2016-08-03-1.Win8log.zip](https://github.com/DaFlight/DaFlight/files/399555/2016-08-03-1.Win8log.zip)

**Comment by AeSix** [comment]
So, yeah I had issues with DaFlight as well.  Forge base with LiteLoader side-loaded, and Optifine as a Forge mod. TabbyChat2 and VoxelMap, both litemods, properly initiate and load.  DaFlight does not. 

I can attempt to get a useful log for you, however my intention here is simply to add support that DaFlight does not work in mixed environments.

**Comment by AeSix** [comment]
As promised, here's the client side log when attempting to use DaFlight:
http://pastie.org/pastes/10928262/text
Notice, I'm not using Sponge anything, that may be part of the issue. 
There's a LOT of errors for everything else, all of which are not present when DaFlight is not in the mods folder.  

Anything else I can do to help, I'll be willing to try.  I've been waiting 2 months for DaFlight to be updated to the version I'm using.  Vanilla flight sucks horribly for admin work, so getting this to work would be amazing!

**Comment by AeSix** [comment]
Here's my startup log without DaFlight. It's a bit cut off, as the game was continuing to load and the log grew long.
http://pastie.org/pastes/10928279/text

**Comment by dags-** [comment]
Your log appears to show daflight loading just fine, although I'm not clear on whether that log is generated from the technic launcher or a modded mojang launcher profile. I'd expect things to load the same in technic, but let me know if not.

'F9' brings up the daflight menu, you can remap controls from there.

---

Flight is designed the way it is to suit my needs (and the server I do dev work for). I share the mod publicly because I think others will still find it useful.

For the best user experience with the mod, the server owner can install the server-side plugin, enable survival mode flight etc. If they don't want to offer that to their users, they don't have to - this is an issue for the user and server owner to work out.

**Comment by AeSix** [comment]
I'm not using technic. that's the other guy. I'm pointing out that DaFlight causes issues with other things as well.  i.e. DaFlight is broken and breaks other things.

**Comment by dags-** [comment]
@AeSix yours is a different issue to do with the 1.10.2 version, I created a separate issue #13 to un-clutter this one

**Comment by AeSix** [comment]
Thank You. 
Also, I understand that you're releasing this to the public even though you're doing the work for yourself.  I appreciate taking the responsibility to sort out issues though.  I'm not a programmer, but I'm a server admin, so I try to give feedback and reports when ever possible.  I'm glad you're willing to listen to us even though everything works fine on your end.  Thank you again! :)

**Comment by craigbrian** [comment]
Only one of my posts was when I did it with the mod pack. Mod pack isn't the problem since this is happening in vanilla with forge, liteloader or both, even using the profile doesn't work.
Okay on vanilla with forge and liteloader on my Windows 8 Alienware pressing F9 the mod lets me change the controls but it still wont work even if I change the controls and I bet if I try it on my Windows 7 HP it will work.

**Comment by craigbrian** [comment]
mod_DaFlight_1.4.1r3_mc1.7.10.litemod  works on all computers
mod_DaFlight_2.0b2_mc1.8.litemod works on all computers
DaFlight-3.2r1-mc1.8.9.jar works only on the Windows 7. F9 works the mod is enabled and it says "loaded" in Liteloader menu.
daflight-4.0r0-mc1.9.jar works only on the Windows 7. F9 works the mod is enabled and it says "loaded" in Liteloader menu.
 daflight-5.0pre2-mc1.10.2.jar works only on the Windows 7. F9 works the mod is enabled and it says "loaded" in Liteloader menu.

Notice all of these problems are with the .jar? even if I use Liteloader or Forge or Both they won't work except on my Windows 7. can you release a .liteloader for all these versions just to test to see if it works?

**Comment by dags-** [comment]
The mod's loading fine, either you have another mod that is preventing flight from working or you don't have permission to fly - the jar versions don't support single player survival/adventure flight, you'd need to be in creative/spectator.

**Comment by craigbrian** [comment]
I did open to Lan but I never thought of being in creative. Thank you so much!
Why does 1.7.10  with fly work on all servers?
and 1.8 fly works on some servers.
I swear this mod used to work on all servers.

**Comment by dags-** [comment]
The way flight works on servers now is just down to how I need it to work
