### ISSUE TITLE
Multiplayer Speed

### ISSUE THREAD

**Issue by FiratAlpaydin** [DaFlight/DaFlight#15]
Hi 1.11.2  1,10,2 multiplayer fly speed and boost doesn't work

**Comment by Bayside308** [comment]
It only works if you're in creative mode.

**Comment by FiratAlpaydin** [comment]
i am in creative mode i can't use boost

**Comment by dags-** [comment]
The server needs to have daflightmanager installed:
https://github.com/DaFlight/DaFlightManager
