### ISSUE TITLE
Other mod interferes with DaFlight speed permissions on multiplayer

### ISSUE THREAD

**Issue by Xeddius** [DaFlight/DaFlight#17]
Boost adds the + to both fly and sprint, however, there is no change to movement whatsoever. Running and flying speed stay at a constant regardless of boost value/settings and activation.
Version: Minecraft 1.12 + Forge + LiteLoader
Only Multiplayer is affected. 
A secondary note:
DaFlightManager 2.2 fails to load on SpongeForge server 1.12.

**Comment by dags-** [comment]
Sponge regularly breaks backwards compatibility with it's plugins, which'll be why DaFlightManager doesn't load, which'll be why you don't see any change in speed.

I'll push an update to DaFlightManager as soon as I can, keep an eye on the releases over there

**Comment by AeSix** [comment]
I've been having the same issue with Spigot 1.12 servers as well. So, not sure it's a Sponge issue.  I've just been dealing with it because i use it for the anti-coasting flight, so I can be accurate with movements.

**Comment by dags-** [comment]
It's working fine on spigot. Either DaFlightManager is not installed on your server, you don't have the permissions to go faster, or another plugin is blocking it

**Comment by Xeddius** [comment]
I can also confirm Spigot and Craftbukkit 1.12 is also not working properly with DaFlightManager/DaFlight. Would it be possible to add a command to DaFlightManager which toggles permissions mode? I'd prefer to allow everyone on my server to fly and boost without restrictions. (The limits put a massive damper for creativity.) (We used to use ZombeMod for it's boost, fly, and radius-xray features when building and DaFlight provides an excellent replacement for the flight feature *and I enjoy the 3D mode as well*.)

Even with proper permissions set in DaFlightManager on both Luckperms and PermissionsEX, boost still doesn't work.

**Comment by dags-** [comment]
Fly/sprint speeds are sent when connecting to the server. Make sure you re-log after adding the permissions.

**Comment by Xeddius** [comment]
I have performed a complete shutdown and startup of the server, all permissions are set correctly daflight.fly.operator and daflight.sprint.operator set, I am in the permission group of operator which also contains the proper daflight permissions and my user is opped as well. There still seems to be no boosting whatsoever. Toggling/restart even with proper permissions has had no effect.

Given the circumstances I believe the issue may be clientside. Perhaps because the client is loading the .jar through liteloader? I will attempt to load DaFlight through other methods to determine if this is the case.

**Comment by dags-** [comment]
Care to provide any logs from your client and server?

**Comment by Xeddius** [comment]
I have bound flight to the X key (toggling it enables flight as desired), Flight and Sprint both work exceptionally well, the only feature that isn't working correctly is the boost speed which is set to 10, however I have attempted other speeds without result. When toggling the boost key the only thing which seems to change is the + at the end of the "Fly" text. Otherwise my blockspeed of 20 blocks per second is unchanged. The DaFlightManager config is set to allow 100 for all permissions as well.

"Commander we should be going like a bat out of hell."

I'll have logs in a minute.

**Comment by dags-** [comment]
yeah post logs from your server and client please

**Comment by Xeddius** [comment]
https://pastebin.com/x7dFbHrJ
From fresh restart it shows nothing. After connection DaFlightManager says "DaFlight connect message received from user Xeddius".
I haven't been able to find anything out of the ordinary in the client logs. But I'm working on getting more details in those.

**Comment by Xeddius** [comment]
Bingo, I've discovered that the boosting works as long as you launch the DaFlight only profile.

Edit: Some LiteLoader mods interfere with the functions of DaFlight. WorldDownloader and AutoFishGUI are the likely culprits. (The only two mods that when enabled cause the flight to stop working correctly)

**Comment by Xeddius** [comment]
Boosting works when in Singleplayer with Both LiteLoader and LiteLoader+Forge.
So something about LiteLoader is modifying the way boosting works or is somehow breaking the message/connection to the server.

**Comment by dags-** [comment]
Of the two, I'd assume it's worlddownloader that is interfering with packets sent to the client
