### ISSUE TITLE
Can't call out GUI with LiteLoader in 1.11.2

### ISSUE THREAD

**Issue by a08381** [DaFlight/DaFlight#18]
[fml-junk-earlystartup.log](http://paste.ubuntu.com/25211323/)

[fml-client-latest.log](http://paste.ubuntu.com/25211321/)

for some personal reasons minecraft forge cannot be used.

![qq 20170731131347](https://user-images.githubusercontent.com/2505002/28763634-23e5ab5e-75f2-11e7-80d9-4f98e2dd3c84.png)

**Comment by dags-** [comment]
daflight should be a `.jar` not `.litemod`
