### ISSUE TITLE
(request) Feature to allow ops to bypass /fly command requirement.

### ISSUE THREAD

**Issue by Xeddius** [DaFlight/DaFlight#21]
It would be nice to add a feature in the config to allow ops (of a configurable level. *2 should be default*) to bypass the need for the /fly command to be entered every login.

**Comment by dags-** [comment]
That'd be up to the plugin that provides the '/fly' command

**Comment by Xeddius** [comment]
I think it may be part of spigot actually, I'll investigate further. Thank you.
