### ISSUE TITLE
can't run the 1.12.2 version

### ISSUE THREAD

**Issue by Raylo555** [DaFlight/DaFlight#23]
literally as soon as I press play it crashes, I guess it's broken?

**Comment by Raylo555** [comment]
also, the only thing i can find in the logs is this;
[07:31:29] [main/INFO]: Loading tweak class name me.dags.daflight.launch.DaFlightTweaker
[07:31:30] [main/INFO]: Using primary tweak class name me.dags.daflight.launch.DaFlightTweaker
[07:31:30] [main/INFO]: Calling tweak class me.dags.daflight.launch.DaFlightTweaker

**Comment by AeSix** [comment]
install liteloader & try¿

**Comment by Raylo555** [comment]
but, i installed the client

**Comment by dags-** [comment]
@Raylo555 hi, I'm guessing this is the same problem as #22, have you tried this version of df:
https://github.com/DaFlight/DaFlight/releases/tag/1.12.2-5.2.2-TEST-0

**Comment by Raylo555** [comment]
is it a client installer? if not no, i haven't

**Comment by dogmadman** [comment]
Hi, I can confirm im getting this issue with 1.12.2, forge 14.23.5.2768

Tried to download https://github.com/DaFlight/DaFlight/releases/tag/1.12.2-5.2.2-TEST-0 but it hits a 404 page. 

looked at issue #22 and tried Forge 14.23.4.2705 but it still crashes on load. Remove DaFlight from mods folder and Minecraft loads

**Comment by AeSix** [comment]
DaFlight works well with LiteLoader for 1.12.2 installed with Forge. 
You can get DaFlight 5.2.2 from here https://github.com/DaFlight/DaFlight/releases

**Comment by dags-** [comment]
@dogmadman 
This is the same problem as #22 it's just I never actually added the fix from the TEST-0 file that I subsequently deleted 🤦‍♂️

Please try 5.2.3:
https://github.com/DaFlight/DaFlight/releases/tag/1.12.2-5.2.3
