### ISSUE TITLE
Feature/Request/Update: Port to RIFT for 1.13.2 support.

### ISSUE THREAD

**Issue by Xeddius** [DaFlight/DaFlight#24]
Given that it may be quite a long time before MCP is released for 1.13.2 and Liteloader (Dependent on mcp), it may be a wise course of action to migrate to the RIFT mod loader for the time being, it's a lightweight api and many other mods have already been ported over. (VoxelMap for example) I believe this to be the best course of action for the time being.

Rift can be found at:
`https://minecraft.curseforge.com/projects/rift`

It should also make updates much easier.

### Making mods work in many Minecraft versions

> With Rift, your mods will work throughout many Minecraft versions. Through optional mod compatibility modules, Rift will remap mods to updated obfuscated names and inject unimplemented vanilla methods back into classes, making the unstable Minecraft API stable. Although compatibility of all mods across many Minecraft versions may not be possible, most mods should work for at least a few versions.

**Comment by dags-** [comment]
DaFlight is what is known as a Tweaker mod - these are mods that can be loaded by Minecraft itself.
Forge, Liteloader, and Rift are all also examples of Tweaker mods.

Not only are Forge and Liteloader able to load ForgeMods and LiteMods respectively, but they can load other Tweaker mods as well. This means one can load the other without Forge needing to be a LiteMod and without Liteloader needing to be a ForgeMod. It also means either can load DaFlight, which is real nice!


Rift, in it's current state, doesn't support loading other Tweaker mods just yet - there's a discussion about it here:
https://github.com/DimensionalDevelopment/Rift/issues/4


It sounds like Rift plans to support a new and upcoming mod loading system called 'ModLauncher', which I believe is this project:
https://github.com/cpw/modlauncher

If I've understood correctly (I'm slightly out of the loop modding-wise), ModLauncher will eventually replace the current Tweaker mod system. With that in mind, it makes sense to adapt DaFlight for this new standard (which shouldn't take much work at all). That way users can choose from any one of Forge, Liteloader, Rift (and whatever other loaders adopt the system), to load DaFlight

**Comment by Xeddius** [comment]
That sounds excellent!
Given that it's a tweakermod, would it be possible to load DaFlight on 1.13.2 with optifine, and if so how would I go about doing so?

**Comment by dags-** [comment]
Not at the moment, I haven't completed updating yet

**Comment by Xeddius** [comment]
I've managed to get every mod I normally use working together using rift except for this mod (which I consider critical for building as it allows for precise movement control without annoying creative flight drift.) Is there a way to get this working with Rift?

**Comment by dags-** [comment]
No ETA on Mixins moving over to the new ModLauncher system.
This version of daflight loads on rift 1.13.2:

[daflight-5.3.0-mc1.13.2-min.jar.zip](https://github.com/DaFlight/DaFlight/files/3156626/daflight-5.3.0-mc1.13.2-min.jar.zip)

**Comment by Xeddius** [comment]
You're awesome, Thank you!

**Comment by AeSix** [comment]
You da badger, Dags!  Thank you!
I'm loading up now and will let you know of any major issues.  The minor ones I'll keep until such time as rift is formally supported, if ever.

**Comment by AeSix** [comment]
I've been playing with this on Rift with Optifine and a hud plugin.  Working great! 
I'd probably say to add a small description to the project front page with a link to the download.  I feel it's stable and working properly :)
