### ISSUE TITLE
1.13.2 Support

### ISSUE THREAD

**Issue by mozartripper** [DaFlight/DaFlight#26]
Hi, I was wondering if you had any success updating the mod to 1.13.2.
I tried to compile it with the included gradlew.bat without success.

**Comment by laztheripper** [comment]
Me too, regular fly is painful :(

**Comment by laztheripper** [comment]
Just wanted to say thanks!! Doing good work and we appreciate it

**Comment by AeSix** [comment]
https://github.com/DaFlight/DaFlight/pull/27

He could probably use more testing from everyone :) 

It's available here: https://github.com/DaFlight/DaFlight/releases

@mozartripper it would be kind of you to close the ticket :)

**Comment by mozartripper** [comment]
Than you guys for working on this mod !
It works great :D
