### ISSUE TITLE
5.3.0 - MC1.13.2 + Forge

### ISSUE THREAD

**Issue by AeSix** [DaFlight/DaFlight#28]
Forge is not loading DaFlight.  Probably since Forge changed greatly, and DF wasn't compiled against it. 

Forge is still in beta, so I understand if this will wait.

**Comment by dags-** [comment]
Forge 1.13 has switched from the 'Tweaker' system to the 'ModLauncher' system. I haven't looked into it in great detail but expect Mixins will need to be updated before DF can move over to it.

**Comment by AeSix** [comment]
@dags- Have you looked at Rift? I don't know if they plan to update past 1.13.2, some stuff from them has referenced Fabric mod for 1.14+  I don't know if Mixins work or are updated for Rift or Fabric.

I know at one point DaFlight worked on LiteLoader - but not since 1.9.4 days, and LiteLoader hasn't been updated in over a year.  Sadness ensures.  Rift really seems to be taking off in popularity though, but that may just be due to lack of options. 

I'd love to be able to update DaFlight to use Rift, but I'm lacking in the knowledge and Java skills.  I can write a "Hello World" app, if I use the tutorials >_>

Thank You for everything you've done for the the community!  DaFlight has really saved Minecraft for me.  I'm currently running a DaFlight only client right now, because it's honestly much more important to me than Optifine, maps, etc.

**Comment by dags-** [comment]
I go into it here:
https://github.com/DaFlight/DaFlight/issues/24

Basically, when 'modlauncher' becomes the standard system you'll be able to use whatever modloader you like to run DaFlight on 1.13 (Rift have already said they'll be switching to modlauncher eventually)

**Comment by AeSix** [comment]
Oh man I'm so sorry I didn't look first. I feel like a real idiot now.

Thank you! :]

I'm closing this since my issues are actually in plans already :)
