### ISSUE TITLE
Info: Updating to 1.14.X - Loaders.

### ISSUE THREAD

**Issue by Xeddius** [DaFlight/DaFlight#30]
Due to internal conflict and code/license issues Rift is no longer being continued. (ugh, I wish there was just ONE that works for everything.)

From this point on the mod community is migrating over to "Fabric". http://fabricmc.net/ has all of the info and tools to port the mods. Understandably this will take some time, but at least Fabric seems stable and looks like it's here to stay.

**Comment by dags-** [comment]
Anything backed by mixins will require minimal effort on my part 👍

**Comment by Xeddius** [comment]
It supports mixins! :D
Also, a small request, since I can use sprint+boost on my server without needing the daflightloader plugin, I would like if you could tweak the plugin to allow flight boosting without the plugin. I have my server configured to allow flight speeds much higher than the default, but without daflightloader I'm always stuck going the default speed.

**Comment by Xeddius** [comment]
Has there been any progress on porting to Fabric or 1.14.X? I hope it hasn't given too much trouble.

**Comment by Xeddius** [comment]
Hey, I hope you've been okay lately. I'm willing to offer an open-source code bounty if it would be of help.

**Comment by Xeddius** [comment]
R.I.P
