### ISSUE TITLE
Mixin issue(s) with Forge

### ISSUE THREAD

**Issue by dags-** [DaFlight/DaFlight#5]
DaFlight Version: [1.8.9-3.1r0](https://github.com/DaFlight/DaFlight/releases/tag/1.8.9-3.1r0)

Crash reports:
https://gist.github.com/dags-/737907c1c7eaa0987ad761f5b5b8e7f6

**Comment by dags-** [comment]
Fixed as of:
5f4642a3ec9ba343831fc72e6bafe3aa4350824c

**Comment by ZeldaLinkAaron** [comment]
This seems to be happening again with 1.9.4 for me 

https://github.com/DaFlight/DaFlight/releases/tag/1.9.4-4.1r0

https://drive.google.com/open?id=0B_5HJyEp3Hp7cjhEZHlaSXZTNGs

**Comment by dags-** [comment]
Can't access the google drive link, please post to gist or pastebin.

Edit: Tested with forge 12.17.0.1940 and it does not produce the start-up error seen in the original issue. Please open as a new issue and provide view-able logs etc
