### ISSUE TITLE
Forge Startup Crash

### ISSUE THREAD

**Issue by ZeldaLinkAaron** [DaFlight/DaFlight#7]
This has also been happening to a few of my friends.

Daflight Version : https://github.com/DaFlight/DaFlight/releases/tag/1.9.4-4.1r0

Error Log: http://pastebin.com/sDiZKnMA

**Comment by dags-** [comment]
Thanks, the error looks to be coming from LiteLoader whilst loading one of the litemods.
Does this crash only occur when you have daflight installed?

**Comment by dags-** [comment]
It may be that the version of Mixins that daflight is packaged with is not compatible with the version of Mixins that liteloader is packaged with, should be an easy enough fix if this is the case

**Comment by ZeldaLinkAaron** [comment]
yea it only happens when using Daflight

**Comment by ZeldaLinkAaron** [comment]
and doesn't happen when not using lightloader

**Comment by ZeldaLinkAaron** [comment]
and doesn't happen when not using Lightloader

**Comment by dags-** [comment]
Cool thanks, yeah does sound like it's a clash between the the Mixin library packaged with daflight and the one packaged with liteloader. I'll put up a new build this weekend

**Comment by ZeldaLinkAaron** [comment]
Cool Thanks as well

**Comment by dags-** [comment]
Should be fixed as of [4.1r1](https://github.com/DaFlight/DaFlight/releases/tag/1.9.4-4.1r1) :]
