### ISSUE TITLE
No Disable Option

### ISSUE THREAD

**Issue by princessbinas** [DaFlight/DaFlight#8]
In the 1.9 version only (as far as I know), this mod is not present in the LiteLoader tab and it is impossible to disable by manual means (i.e. removing from the mods folder). Please fix this issue.

**Comment by dags-** [comment]
This is just nonsense.

If you bothered to read the usage information on planetminecraft or mcforums then you would have read that pressing 'F9' opens the daflight menu, in which you can disable the mod

If you have installed the mod by placing it in the mods folder, and load it with a modloader like liteloader, then deleting it from the mods folder **does** work as means of uninstalling it.

If you have installed the mod as a profile (ie with the installer) then just create a different profile.

**Comment by princessbinas** [comment]
I did read it and I did press F9, and nothing happened.

And I did that, but the flight is still occurring even with the mod not present in the folder.

I just put it into the mods folder like all other LiteLoader mods. Not as a profile.

**Comment by dags-** [comment]
If flight is occurring after deleting daflight from your mods folder, then you must have another mod installed that is causing it.

If you upload your log file to somewhere like pastebin I could take a look at it and maybe work out what's causing you to fly

**Comment by princessbinas** [comment]
I don't have any other flight mods on my computer. All I have is voxel map, x-ray, world downloader, and auto fishing.

I recently reset MC due to horrible lag issue (it has been happening before your mod by the way), so the original log is gone. So I tried recreating what I did in hopes of getting the results you need for analyzing. In the end, I failed. It was a rare bug that I had encountered the first go around.

As for the things I did, one of them was that I put the installer in the mods folder. However, I never changed the profile to daflight's (I remained using the 1.8 liteloader profile after doing both, extracting and profile creation), but I did go into a creative world before into a multiplayer.
